### ISSUE TITLE
Is this fastboot compatible?

### ISSUE THREAD

**Issue by iamareebjamal** [Exelord/ember-await#4]
Hi, we use fastboot heavily on our site. Is the library fastboot ready? If not, what can be done to make it so, I'd be happy to contribute

**Comment by Exelord** [comment]
I think the only thing that is not compatible is AbortController. But I guess that could be shimmed.

**Comment by Exelord** [comment]
We would need sth like this: 
https://github.com/ember-cli/ember-fetch/blob/master/index.js#L169

**Comment by Exelord** [comment]
But... I may be wrong. As far I know fastboot does not wait for components to resolve. It only resolves model hook from routes. So with that In mind I think ember-await can be actually fully compatible with fastboot out of the box :)

**Comment by Exelord** [comment]
From v0.5.2 ember await is now Fastboot compatible :) It does not resolve the data on the server, but it does not break the rendering anymore. 

Blocking fastboot render until the data has been fetched would require new API for fastboot to be implemented. So, for now, we cannot do any better :/
