### ISSUE TITLE
Problems resolving Await component

### ISSUE THREAD

**Issue by imagolive** [Exelord/ember-await#5]
Very excited to use this, but the component does not seem to be resolved properly.

![image](https://user-images.githubusercontent.com/23182810/84116328-2e635480-aa62-11ea-853d-964075c81cdd.png)

It appears in the add-on tree:

![image](https://user-images.githubusercontent.com/23182810/84116364-43d87e80-aa62-11ea-90c6-0e1fcdc2c3d8.png)

It seems like the resolver might be getting confused because the component uses a pod structure (perhaps) instead of the colocated component structure.

**Comment by imagolive** [comment]
Had a go at rearranging things so they resolved. Easy fix in the end.

There is a PR but it is asking for signed commits. Started reading doco, too many commands and ran out of time.

The change is simply to rename the files like:

![image](https://user-images.githubusercontent.com/23182810/84121270-83ef2f80-aa69-11ea-94ee-c0d704ec76a8.png)

No code needs to be modified.

**Comment by knownasilya** [comment]
Same issue here

**Comment by Exelord** [comment]
Solved by #6
