### ISSUE TITLE
Handling pagination

### ISSUE THREAD

**Issue by simonc** [Exelord/ember-await#7]
Hi!

I've started using ember-await on a project and so far everything has been great. One issue I'm facing though is introducing pagination. Using the classic Ember way you'd define a `page` query-param on the Route and Controller and refresh the model when it changes.

What would be your recommendation to deal with this?

Thanks! ❤️

**Comment by Exelord** [comment]
Hey Siomn :) 

For now that's beyond ember-await responsibility. You can handle that on promise level. Every time you will change the promise arg the Await block will be evaluated.

You could use a computed prop to pass proper promise based on page param eg:
```
get fetchSth() {
  return () => fetch(URL, { params: { page: this.page } })
}
```
that way whenever the pagination will change the promise will be refreshed. 

You can also use defer arg for that purpose but I would not to recommend it as first choice.

if you are using the route's model for fetching, that should be handled automatically. Just pass ensure the model is returning a async function and you set the QP to refresh model.

```
export default class ArticlesRoute extends Route {
  queryParams = {
    category: {
      refreshModel: true
    }
  };

  model(params) {
    return () => this.store.query('article', params);
  }
}
```

Why returning a function not just a promise? When doing so you will get extra capabilities like the ability to reload the promise in the await component.

**Comment by simonc** [comment]
Hey @Exelord, thanks for you answer.

I was using a data-loading component so it was not playing nice with using proper links, etc. I switched back to what you proposed, defining the request as Route model and returning a function. It worked like a charm 🙂

Thanks! ❤️
