### ISSUE TITLE
error with args proxy

### ISSUE THREAD

**Issue by gossi** [Exelord/ember-await#8]
I tried ember-await today, but got an error message. Which in full length is this:

```
Uncaught (in promise) Error: Assertion Failed: args proxies do not have real property descriptors, so you should never need to call getOwnPropertyDescriptor yourself. This code exists for enumerability, such as in for-in loops and Object.keys()
```

The stack trace didn't help here with more information. I was trying different promises but all led to the same error:

```
@task
load = task(function* (this: MyComponent) {
  return this.args.data;
});

// ...

load() {
  return new Promise(resolve => {
    resolve(this.args.data);
  });
}


// ...

load() {
  return new Promise(resolve => {
    resolve();
  });
}
```

for the first two I thought something is wrong with _my_ `args` here but receiving the error on the third case I was sure it wasn't. So I read up on the ember-await code and may have some ideas what might be the cause. My feeling is ember's/glimmer's internal tracking system is the reason. It is not well treated and I think the reason for that is the usage of observers: 

https://github.com/Exelord/ember-await/blob/f920ab182b33f9e66f9e6b64e609242500658020/addon/components/await/component.js#L23

and

https://github.com/Exelord/ember-await/blob/f920ab182b33f9e66f9e6b64e609242500658020/addon/components/await/component.js#L34

The better way would be to use [`ember-render-helpers`](https://github.com/buschtoens/ember-render-helpers) instead. The code then would look like this:

```js
class AwaitComponent extends Component {
  query;

  /**
   * Observes `promise` argument and triggers promiseTask in case of change
   * and during first initialization
   * @memberof AwaitComponent
   */
  constructor() {
    super(...arguments);

    this.query = new Query(this.args);
  }

  @action
  updateQuery() {
    this.query.reload();
  }

  @action
  cleanup() {
    this.query.cancel();
  }

  @task({ drop: true })
  *runTask(runFn) {
    return yield this.query.run(runFn);
  }

  @action
  run(...args) {
    const { defer } = this.args;

    if (!('defer' in this.args)) return;

    return this.runTask.perform((controller) => callback(defer)(args, controller));
  }
}
```

with it's template:

```hbs
{{did-insert this.updateQuery}} {{! if needed}}
{{did-update this.updateQuery}}
{{will-destroy this.cleanup}}
// ...
```

Even if this is the reason or not, I'd encourage a change here 😂

Second idea is in the access of props from `args` as to the error message but I didn't dig deeper in here.

**Comment by Exelord** [comment]
As we discussed that issue seems to not be related to Ember Await. Its rather project-specific (possibly not supported ember version). :) 

Regarding the ember render helpers add-on, its an extra dependency with no real profit. The same behavior has been achieved with an observer. I can't see any benefit that addon could bring for Ember Await users, where on the other side it brings extra cost. :/
